kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.22.2
    extraPortMappings:
      - containerPort: 5000
        hostPort: 5000
      - containerPort: 80
        hostPort: 80 